### ISSUE TITLE
Standardize front end sorting

### ISSUE THREAD

**Issue by sergeyager** [bvanvugt/canadian-streamers#5]
Currently it looks like streamers are returned in a random order.

Suggestion:

Online streamers on top
* alphabetical

Offline streamers below:
* alphabetical

Alternate ordering:
* last time streamed

**Comment by bvanvugt** [comment]
Yeah I wasn't sure what's best here. Current sorting is:
* Online, randomized
* Offline, randomized

The goal being to promote all streams in a "fairly" by randomizing display order. But I agree it's jarring...

I can make some assumptions but what's the motivation for non-random sorting?

**Comment by bvanvugt** [comment]
Okay, for now I've gone alphabetical on both lists. I like the idea of sorting the offline list by last streamed date but it'll take a bunch more effort to get that info. I'll add this request to that issue.
